import webbrowser
import re
import time
# mixin_handlers.py
# Signal callbacks, settings, misc UI state, and export methods
# for DropCatcher.
# Generated by split_step5_handlers.py — do not hand-edit method bodies here;
# make changes in main.py first, then re-run the split scripts.
import csv
import threading
from datetime import datetime

from PyQt5.QtWidgets import (
    QApplication, QSystemTrayIcon, QMenu, QMessageBox, QFileDialog, QTableWidgetItem,
)
from PyQt5.QtCore import Qt, QTime
from PyQt5.QtGui import QColor

from sniper import set_priority_enabled, POLL_MODES
from api import check_domain
from constants import (
    COL_DROP, COL_PRICE, COL_STATUS, COL_WHOIS, COL_NEXT,
    MONITOR_MAX_USER_RPS_DELAY, MONITOR_MIN_PER_DOMAIN_INTERVAL,
)
from utils import (
    normalize_domain,
    get_tld_price,
    estimate_drop_date,
    _extract_expiry_from_raw_whois,
    _first_datetime,
    _norm_status,
)
from persistence import load_settings, save_settings, save_watchlist


class HandlersMixin:
    """Mixin: signal callbacks, settings, misc UI state, and export methods."""

    def closeEvent(self, e):
        if self.settings.get("minimize_to_tray", True):
            e.ignore()
            self.hide()
            self.tray.showMessage(
                "Still running",
                "Drop Catcher is still monitoring in the system tray.",
                QSystemTrayIcon.Information,
                3000,
            )
        else:
            self.monitor_scheduler_stop.set()
            self.monitor_scheduler_wake.set()
            self.whois_worker_stop.set()
            self.whois_worker_wake.set()
            e.accept()

    def _setup_tray(self):
        self.tray = QSystemTrayIcon(self)
        self.tray.setVisible(True)
        m = QMenu()
        m.addAction("Open", self.show)
        m.addAction("Quit", QApplication.quit)
        self.tray.setContextMenu(m)
        self.tray.activated.connect(lambda r: self.show() if r == QSystemTrayIcon.DoubleClick else None)

    def _apply_settings(self):
        self.setWindowFlag(Qt.WindowStaysOnTopHint, self.settings.get("always_on_top", False))
        self.show()

    def _toggle_on_top(self, v):
        self._save_setting("always_on_top", v)
        self.setWindowFlag(Qt.WindowStaysOnTopHint, v)
        self.show()

    def _save_setting(self, key, val):
        self.settings[key] = val
        save_settings(self.settings)

    def _load_rampage_queue(self):
        from persistence import load_rampage_queue as _load_rq
        return _load_rq()
    def _save_rampage_queue(self):
        from persistence import saverampagequeue as _save_rq
        _save_rq(list(self.rampage_rows.keys()))
    def _get_poll_interval(self):
        mode = self.poll_mode.currentText()
        if mode == "Custom":
            return max(1, self.custom_secs.value())
        return POLL_MODES.get(mode, 60)

    def _effective_monitor_domain_interval(self):
        return max(MONITOR_MIN_PER_DOMAIN_INTERVAL, float(self._get_poll_interval()))

    def _monitor_global_delay(self):
        active = max(1, self._count_active_monitor_domains())
        cycle_target = self._effective_monitor_domain_interval()
        spacing = cycle_target / active
        spacing = max(MONITOR_MAX_USER_RPS_DELAY, spacing)
        return spacing

    def _update_monitor_delay_label(self):
        active = self._count_active_monitor_domains()
        if active <= 0:
            self.monitor_delay_label.setText("Queue: idle")
        else:
            self.monitor_delay_label.setText(
                f"Queue: {self._monitor_global_delay():.1f}s/request | {self._effective_monitor_domain_interval():.0f}s/domain"
            )

    def _on_poll_mode_changed(self, mode):
        self.custom_secs.setVisible(mode == "Custom")
        if "Aggressive" in mode:
            self.mode_badge.setText("🟡 Aggressive (10s)")
            self.mode_badge.setStyleSheet("color:#fbbf24;font-weight:bold;padding:0 8px;")
        elif "Fast" in mode:
            self.mode_badge.setText("🔵 Fast (30s)")
            self.mode_badge.setStyleSheet("color:#60a5fa;font-weight:bold;padding:0 8px;")
        else:
            self.mode_badge.setText(f"🟢 {mode}")
            self.mode_badge.setStyleSheet("color:#4ade80;font-weight:bold;padding:0 8px;")
        self._wake_monitor_scheduler()

    def _on_priority_toggled(self, enabled):
        set_priority_enabled(enabled)
        self.append_log(f"Priority weighting {'enabled' if enabled else 'disabled'}.")

    def _event_key(self, domain, mode):
        return f"{mode}:{domain}"

    def _stop_event_for(self, domain, mode):
        return self._stop_events.get(self._event_key(domain, mode))

    def _set_stop_event_for(self, domain, mode, stop_event):
        self._stop_events[self._event_key(domain, mode)] = stop_event

    def _pop_stop_event_for(self, domain, mode):
        return self._stop_events.pop(self._event_key(domain, mode), None)

    def _check_scheduled(self):
        if not self.schedule_check.isChecked():
            self._sched_armed_for_minute = None
            return

        now = QTime.currentTime()
        minute_key = now.toString("HH:mm")
        target = self.schedule_time.time().toString("HH:mm")

        if minute_key == target and self._sched_armed_for_minute != minute_key:
            self._sched_armed_for_minute = minute_key
            self.start_rampage_all()
            self.append_log("Scheduled Rampage started.")
            self.tray.showMessage(
                "Rampage",
                "Scheduled drop window reached - Rampage queue started.",
                QSystemTrayIcon.Information,
                5000,
            )
        elif minute_key != target:
            self._sched_armed_for_minute = None

    def _tick_countdowns(self):
        now = time.time()
        self._paint_next_countdowns(self.monitor_table, self.monitor_rows, self.monitor_next_ts, now)
        self._paint_next_countdowns(self.rampage_table, self.rampage_rows, self.rampage_next_ts, now)

    def _paint_next_countdowns(self, table, rows, nextmap, now):
        for domain, ts in list(nextmap.items()):
            row = rows.get(domain)
            if row is None:
                continue
            rem = ts - now
            txt = f"{int(rem)}s" if rem > 0 else "now"
            color = QColor("#fbbf24") if 0 < rem <= 5 else QColor("#f87171") if rem <= 0 else QColor("#64748b")
            item = QTableWidgetItem(txt)
            item.setForeground(color)
            item.setTextAlignment(Qt.AlignCenter)
            table.setItem(row, COL_NEXT, item)

    def _store_next_check(self, domain, ts, mode):
        if mode == "rampage":
            self.rampage_next_ts[domain] = ts
        else:
            self.monitor_next_ts[domain] = ts

    def _whois_interval_value(self):
        return {
            "10 seconds": 10,
            "30 seconds": 30,
            "1 minute": 60,
            "2 minutes": 120,
            "5 minutes": 300,
        }.get(self.whois_interval_cb.currentText(), 60)

    def _tick_whois_countdown(self):
        self.whois_remaining = max(0, self.whois_remaining - 1)
        pct = int(100 * self.whois_remaining / max(1, self.whois_interval_secs))
        self.whois_progress.setValue(pct)
        self.whois_progress.setFormat(f"Next check in {self.whois_remaining}s" if self.whois_remaining > 0 else "Checking...")

    def _run_whois_manual(self):
        d = normalize_domain(self.whois_input.text())
        if not d:
            return
        self.whois_output.setPlainText(f"Checking {d}...")
        self._enqueue_whois(d, "tab")

    def _show_whois_result(self, key, result):
        parts = key.split("|", 3)
        domain = parts[0]
        mode = parts[1] if len(parts) > 1 else "row"
        drop_est = parts[2] if len(parts) > 2 else "-"
        status_norm = parts[3] if len(parts) > 3 else ""

        if mode == "tab":
            self.whois_output.setPlainText(result)
            return

        short = "Unknown"
        color = QColor("#64748b")

        if "pendingdelete" in status_norm:
            short, color = "pendingDelete", QColor("#f87171")
        elif any(k in status_norm for k in ("redemptionperiod", "pendingrenewaldeletion", "redemption")):
            short, color = "Redemption", QColor("#f59e0b")
        elif "active" in status_norm or status_norm == "ok":
            short, color = "Active", QColor("#94a3b8")
        elif "whoiserror" in status_norm:
            short, color = "WHOIS err", QColor("#f87171")

        self._set_item_if_present(self.monitor_table, self.monitor_rows, domain, COL_WHOIS, self._center_item(short, color.name()))
        self._set_item_if_present(self.monitor_table, self.monitor_rows, domain, COL_DROP, self._center_item(drop_est, color.name()))
        self._set_item_if_present(self.rampage_table, self.rampage_rows, domain, COL_WHOIS, self._center_item(short, color.name()))
        self._set_item_if_present(self.rampage_table, self.rampage_rows, domain, COL_DROP, self._center_item(drop_est, color.name()))

        if mode == "auto":
            ts = datetime.now().strftime("%H:%M:%S")
            self.whois_auto_log.append(f"[{ts}] {domain} | {short} | {drop_est}")

    def run_premium_check(self, domain):
        self._set_status_in_tables(domain, "Checking premium...", "#93c5fd")
        threading.Thread(target=self._premium_check_worker, args=(domain,), daemon=True).start()

    def _premium_check_worker(self, domain):
        try:
            info = check_domain(domain) or {}
            self.signals.premium_check_result.emit(domain, info)
        except Exception as e:
            self.signals.premium_check_result.emit(domain, {"error": str(e)})

    def _show_premium_result(self, domain, info):
        if not isinstance(info, dict):
            self._set_status_in_tables(domain, "Premium check failed", "#f87171")
            self.append_log(f"Premium check failed for {domain}.")
            return

        if info.get("error"):
            self._set_status_in_tables(domain, f"Premium check error: {str(info['error'])[:60]}", "#f87171")
            self.append_log(f"Premium check error for {domain}: {info['error']}")
            return

        is_premium = bool(info.get("is_premium"))
        price = info.get("premium_price")
        currency = info.get("premium_currency", "USD")

        if is_premium and price:
            try:
                price_f = float(price)
                self._update_price_col(domain, f"{currency} {price_f:.2f}")
                self._set_status_in_tables(domain, f"Premium {currency} {price_f:.2f}", "#f59e0b")
                self.append_log(f"{domain} is premium: {currency} {price_f:.2f}")
            except Exception:
                self._set_status_in_tables(domain, f"Premium {price}", "#f59e0b")
                self.append_log(f"{domain} is premium: {price}")
        else:
            self._set_status_in_tables(domain, "Not premium", "#4ade80")
            self.append_log(f"{domain} is not premium.")

    def _update_price_col(self, domain, text):
        self._set_item_if_present(self.monitor_table, self.monitor_rows, domain, COL_PRICE, self._center_item(text, "#4ade80"))
        self._set_item_if_present(self.rampage_table, self.rampage_rows, domain, COL_PRICE, self._center_item(text, "#4ade80"))

    def _update_status(self, domain, status):
        color = "#93c5fd"
        s = str(status or "").lower()

        if "available" in s or "success" in s or "caught" in s:
            color = "#4ade80"
        elif "error" in s or "failed" in s:
            color = "#f87171"
        elif "rate" in s or "cool" in s or "premium" in s:
            color = "#f59e0b"
        elif "stopped" in s or "idle" in s:
            color = "#94a3b8"

        self._set_status_in_tables(domain, status, color)
        self.footer_lbl.setText(f"{domain}: {status}")
        self.refresh_stats()

    def _handle_success(self, domain, reg):
        self.stop_domain(domain)

        name = reg.get("name") or domain
        status = reg.get("status", "PENDING")
        paid = reg.get("price") or reg.get("charged") or get_tld_price(domain)

        self._set_status_in_tables(domain, f"Caught ({status})", "#4ade80")
        self.append_log(f"SUCCESS {name} caught.")
        self.tray.showMessage(
            "Domain caught",
            f"{name} registration submitted successfully.",
            QSystemTrayIcon.Information,
            5000,
        )

        row = self.portfolio_table.rowCount()
        self.portfolio_table.insertRow(row)
        self.portfolio_table.setItem(row, 0, QTableWidgetItem(name))
        self.portfolio_table.setItem(row, 1, QTableWidgetItem(datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
        self.portfolio_table.setItem(row, 2, QTableWidgetItem(str(paid)))
        self.portfolio_table.setItem(row, 3, QTableWidgetItem(str(status)))
        self.portfolio_table.setItem(row, 4, QTableWidgetItem(""))

        self.caught.append({
            "domain": name,
            "caughtat": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "pricepaid": str(paid),
            "status": str(status),
            "notes": "",
        })
        self.refresh_stats()

    def _handle_failure(self, domain, detail):
        self.stop_domain(domain)
        self._set_status_in_tables(domain, f"Failed: {detail}", "#f87171")
        self.append_log(f"FAIL {domain}: {detail}")
        self.tray.showMessage(
            "Registration failed",
            f"{domain}: {detail}",
            QSystemTrayIcon.Warning,
            5000,
        )
        self.refresh_stats()

    def _handle_premium(self, domain, price, currency):
        self.stop_domain(domain, "monitor")

        max_premium = int(self.settings.get("max_premium", 500) or 0)
        self._update_price_col(domain, f"{currency} {price:.2f}")
        self._set_status_in_tables(domain, f"Premium detected {currency} {price:.2f}", "#f59e0b")

        if max_premium > 0 and price > max_premium:
            self.append_log(f"{domain} premium too high: {currency} {price:.2f} > {max_premium}. Skipped.")
            self._set_status_in_tables(domain, f"Skipped premium {currency} {price:.2f}", "#f59e0b")
            return

        answer = QMessageBox.question(
            self,
            "Premium Domain Detected",
            f"{domain} is premium ({currency} {price:.2f}). Add to Rampage queue?",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.Yes,
        )

        if answer == QMessageBox.Yes:
            if self._add_rampage_row(domain):
                self._save_rampage_queue()
                self.append_log(f"{domain} moved to Rampage queue after premium detection.")
            self._set_status_in_tables(domain, f"Premium queued {currency} {price:.2f}", "#f59e0b")
            self.sniper_tabs.setCurrentIndex(1)
        else:
            self.append_log(f"{domain} premium declined by user.")
            self._set_status_in_tables(domain, f"Premium declined {currency} {price:.2f}", "#94a3b8")

    def append_log(self, text):
        ts = datetime.now().strftime("%H:%M:%S")
        self.log.append(f"[{ts}] {text}")
        if self.log.document().blockCount() > self._LOG_MAX_LINES:
            lines = self.log.toPlainText().splitlines()
            self.log.setPlainText("\n".join(lines[-self._LOG_MAX_LINES:]))
            self.log.verticalScrollBar().setValue(
                self.log.verticalScrollBar().maximum()
            )

    def _update_clock(self):
        self.clock_lbl.setText(datetime.now().strftime("%H:%M:%S  %d.%m.%Y"))

    def clear_watchlist(self):
        domains = list(self.monitor_rows.keys())
        for d in domains:
            self.stop_domain(d, "monitor")
        self.monitor_table.setRowCount(0)
        self.monitor_rows.clear()
        self.monitor_next_ts.clear()
        with self.monitor_scheduler_lock:
            self.monitor_runtime.clear()
        save_watchlist([])
        self.refresh_stats()
        self.append_log("Monitoring cleared.")

    def export_csv(self):
        path, _ = QFileDialog.getSaveFileName(self, "Export caught CSV", "caughtdomains.csv", "CSV Files (*.csv)")
        if not path:
            return
        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["domain", "caughtat", "pricepaid", "status", "notes"])
            for row in range(self.portfolio_table.rowCount()):
                vals = []
                for col in range(5):
                    item = self.portfolio_table.item(row, col)
                    vals.append(item.text() if item else "")
                w.writerow(vals)
        self.append_log(f"Portfolio CSV exported: {path}")

    def export_portfolio(self):
        self.export_csv()

    def _clear_portfolio(self):
        self.portfolio_table.setRowCount(0)
        self.caught.clear()
        self.refresh_stats()
        self.append_log("Portfolio cleared.")

    def generate_ai_prompt(self):
        tokens = [normalize_domain(t) for t in re.split(r"[\s,;]+", self.ai_input.toPlainText())]
        domains = [d for d in tokens if d]
        if not domains:
            self.ai_preview.setPlainText("")
            return

        prompt = (
            "Analyze the following domains for brandability, resale potential, "
            "end-user demand, and likely liquidity. Return a compact investor-oriented "
            "ranking with reasons, risks, and a suggested shortlist for immediate action.\n\n"
            "Domains:\n- " + "\n- ".join(domains)
        )
        self.ai_preview.setPlainText(prompt)
        QApplication.clipboard().setText(prompt)
        self.append_log(f"Generated AI prompt for {len(domains)} domains.")
